### ISSUE TITLE
Model component errors need to account for spatial model requirements

### ISSUE THREAD

**Issue by BryanRumsey** [StochSS/stochss#1143]
## Tasks
 - [x] Remove species collection error `div` from `spatialSpeciesEditor.pug`
 - [x] Add check for spatial model to `toggleSpeciesCollectionError` function in `species-editor.js`
 - [x] Add check for spatial model to `toggleProcessError` function in `reaction-editor.js`
 - [x] Add check for spatial model to the species collection validation function.
 - [x] Add check for spatial model to the models validation function.
